<?php
$xmlStr = "<pre>&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;

&lt;!--
	Generated by e-racuni.com

	Release number: 872.9
	Release date: 19.09.2021
	Request URL: /WebServicesHR/API
--&gt;

&lt;response status=&quot;ok&quot;&gt;
	&lt;SalesInvoice&gt;
		&lt;advanceInvoicesRef&gt;&lt;/advanceInvoicesRef&gt;
		&lt;amountAlreadyPaid&gt;-90&lt;/amountAlreadyPaid&gt;
		&lt;amountLeftToBePaid&gt;0&lt;/amountLeftToBePaid&gt;
		&lt;bankAccountNumber&gt;HR5623600001101883472&lt;/bankAccountNumber&gt;
		&lt;businessUnit&gt;0000&lt;/businessUnit&gt;
		&lt;businessYear&gt;2019&lt;/businessYear&gt;
		&lt;buyerCountry&gt;HR&lt;/buyerCountry&gt;
		&lt;buyerName&gt;&lt;/buyerName&gt;
		&lt;buyerVatRegistration&gt;Unknown&lt;/buyerVatRegistration&gt;
		&lt;cancelledByDocumentsRef&gt;&lt;/cancelledByDocumentsRef&gt;
		&lt;city&gt;Zagreb&lt;/city&gt;
		&lt;costPosition&gt;&lt;/costPosition&gt;
		&lt;creditNotesRef&gt;&lt;/creditNotesRef&gt;
		&lt;date&gt;2019-02-04&lt;/date&gt;
		&lt;dateOfSupplyFrom&gt;2019-02-04&lt;/dateOfSupplyFrom&gt;
		&lt;debitNotesRef&gt;&lt;/debitNotesRef&gt;
		&lt;deliveryNotesRef&gt;&lt;/deliveryNotesRef&gt;
		&lt;documentID&gt;60:2980554&lt;/documentID&gt;
		&lt;domesticCurrency&gt;HRK&lt;/domesticCurrency&gt;
		&lt;expirationDate&gt;2019-02-04&lt;/expirationDate&gt;
		&lt;isReccurringInvoice&gt;false&lt;/isReccurringInvoice&gt;
		&lt;issuedTimestamp&gt;8:39&lt;/issuedTimestamp&gt;
		&lt;issuedTimestampDate&gt;2019-02-04&lt;/issuedTimestampDate&gt;
		&lt;methodOfPayment&gt;BankTransfer&lt;/methodOfPayment&gt;
		&lt;number&gt;96/0000/191&lt;/number&gt;
		&lt;operaterName&gt;Ivan Novak&lt;/operaterName&gt;
		&lt;paymentDueDate&gt;2019-02-04&lt;/paymentDueDate&gt;
		&lt;reference&gt;01 119962&lt;/reference&gt;
		&lt;remarks&gt;Broj računa: 7&lt;/remarks&gt;
		&lt;salesOrdersRef&gt;&lt;/salesOrdersRef&gt;
		&lt;status&gt;IssuedInvoice&lt;/status&gt;
		&lt;totalAmount&gt;-90&lt;/totalAmount&gt;
		&lt;totalAmountInDomCurr&gt;-90&lt;/totalAmountInDomCurr&gt;
		&lt;totalAmountInVatReportingCurr&gt;-90&lt;/totalAmountInVatReportingCurr&gt;
		&lt;totalCurrency&gt;HRK&lt;/totalCurrency&gt;
		&lt;totalDiscount&gt;-10&lt;/totalDiscount&gt;
		&lt;totalNetAmount&gt;-90&lt;/totalNetAmount&gt;
		&lt;totalNetAmountInDomCurr&gt;-90&lt;/totalNetAmountInDomCurr&gt;
		&lt;totalNetAmountInVatReportingCurr&gt;-90&lt;/totalNetAmountInVatReportingCurr&gt;
		&lt;totalVatAmountInDomCurrLowerRate&gt;0&lt;/totalVatAmountInDomCurrLowerRate&gt;
		&lt;totalVatAmountInDomCurrLowerRate2&gt;0&lt;/totalVatAmountInDomCurrLowerRate2&gt;
		&lt;totalVatAmountInDomCurrNormalRate&gt;0&lt;/totalVatAmountInDomCurrNormalRate&gt;
		&lt;totalVatAmountInDomCurrZeroRate&gt;0&lt;/totalVatAmountInDomCurrZeroRate&gt;
		&lt;totalVatAmountInVatReportingCurrLowerRate&gt;0&lt;/totalVatAmountInVatReportingCurrLowerRate&gt;
		&lt;totalVatAmountInVatReportingCurrLowerRate2&gt;0&lt;/totalVatAmountInVatReportingCurrLowerRate2&gt;
		&lt;totalVatAmountInVatReportingCurrNormalRate&gt;0&lt;/totalVatAmountInVatReportingCurrNormalRate&gt;
		&lt;totalVatAmountInVatReportingCurrZeroRate&gt;0&lt;/totalVatAmountInVatReportingCurrZeroRate&gt;
		&lt;totalVatAmountLowerRate&gt;0&lt;/totalVatAmountLowerRate&gt;
		&lt;totalVatAmountLowerRate2&gt;0&lt;/totalVatAmountLowerRate2&gt;
		&lt;totalVatAmountNormalRate&gt;0&lt;/totalVatAmountNormalRate&gt;
		&lt;totalVatAmountZeroRate&gt;0&lt;/totalVatAmountZeroRate&gt;
		&lt;totalVatBaseAmountInDomCurrLowerRate&gt;0&lt;/totalVatBaseAmountInDomCurrLowerRate&gt;
		&lt;totalVatBaseAmountInDomCurrLowerRate2&gt;0&lt;/totalVatBaseAmountInDomCurrLowerRate2&gt;
		&lt;totalVatBaseAmountInDomCurrNormalRate&gt;0&lt;/totalVatBaseAmountInDomCurrNormalRate&gt;
		&lt;totalVatBaseAmountInDomCurrZeroRate&gt;-90&lt;/totalVatBaseAmountInDomCurrZeroRate&gt;
		&lt;totalVatBaseAmountInVatReportingCurrLowerRate&gt;0&lt;/totalVatBaseAmountInVatReportingCurrLowerRate&gt;
		&lt;totalVatBaseAmountInVatReportingCurrLowerRate2&gt;0&lt;/totalVatBaseAmountInVatReportingCurrLowerRate2&gt;
		&lt;totalVatBaseAmountInVatReportingCurrNormalRate&gt;0&lt;/totalVatBaseAmountInVatReportingCurrNormalRate&gt;
		&lt;totalVatBaseAmountInVatReportingCurrZeroRate&gt;-90&lt;/totalVatBaseAmountInVatReportingCurrZeroRate&gt;
		&lt;totalVatBaseAmountLowerRate&gt;0&lt;/totalVatBaseAmountLowerRate&gt;
		&lt;totalVatBaseAmountLowerRate2&gt;0&lt;/totalVatBaseAmountLowerRate2&gt;
		&lt;totalVatBaseAmountNormalRate&gt;0&lt;/totalVatBaseAmountNormalRate&gt;
		&lt;totalVatBaseAmountZeroRate&gt;-90&lt;/totalVatBaseAmountZeroRate&gt;
		&lt;type&gt;Retail&lt;/type&gt;
		&lt;vatOutgoingDocumentVatClause&gt;RegisteredVATr2&lt;/vatOutgoingDocumentVatClause&gt;
		&lt;vatReportingCurrency&gt;HRK&lt;/vatReportingCurrency&gt;
		&lt;vatTransactionType&gt;0&lt;/vatTransactionType&gt;
		&lt;warehouseCode&gt;VS&lt;/warehouseCode&gt;
		&lt;wayOfPayment&gt;BankTransfer&lt;/wayOfPayment&gt;
		&lt;Items&gt;
			&lt;Item&gt;
				&lt;amount&gt;-90&lt;/amount&gt;
				&lt;amountWithoutDiscount&gt;-100&lt;/amountWithoutDiscount&gt;
				&lt;costPosition&gt;&lt;/costPosition&gt;
				&lt;currency&gt;HRK&lt;/currency&gt;
				&lt;description&gt;EMNG gornjih udova&lt;/description&gt;
				&lt;discountAmount&gt;-10&lt;/discountAmount&gt;
				&lt;discountPercentage&gt;10&lt;/discountPercentage&gt;
				&lt;netPrice&gt;-100&lt;/netPrice&gt;
				&lt;netPriceInDocumentCurrency&gt;-100&lt;/netPriceInDocumentCurrency&gt;
				&lt;position&gt;1&lt;/position&gt;
				&lt;price&gt;-100&lt;/price&gt;
				&lt;priceInDocumentCurrency&gt;-100&lt;/priceInDocumentCurrency&gt;
				&lt;quantity&gt;1&lt;/quantity&gt;
				&lt;totalDiscountPercentage&gt;10&lt;/totalDiscountPercentage&gt;
				&lt;unit&gt;kom&lt;/unit&gt;
				&lt;vatAmount&gt;0&lt;/vatAmount&gt;
				&lt;vatPercentage&gt;0&lt;/vatPercentage&gt;
			&lt;/Item&gt;
		&lt;/Items&gt;
	&lt;/SalesInvoice&gt;

&lt;/response&gt;</pre>";



echo $xmlStr;




?>